In [1]:
%matplotlib inline

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

pd.set_option('display.mpl_style', 'default') # Make the graphs a bit prettier
plt.rcParams['figure.figsize'] = (15, 5)
plt.rcParams['font.family'] = 'sans-serif'

# This is necessary to show lots of columns in pandas 0.12. 
# Not necessary in pandas 0.13.
pd.set_option('display.width', 5000) 
pd.set_option('display.max_columns', 60)

C:\ProgramData\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py:2881: FutureWarning: 
mpl_style had been deprecated and will be removed in a future version.
Use `matplotlib.pyplot.style.use` instead.

  exec(code_obj, self.user_global_ns, self.user_ns)


In [2]:
temp_df = pd.read_csv('test.csv', parse_dates=['Date'], dayfirst=True)

In [3]:
temp_df['Latitude'].unique()

array([ 41.86407316,  41.78292153,  41.89490828,  41.88568685,
        41.88629724,  41.74535402,  41.84402377,  41.81113396,
        41.99813061,  41.76809684,  41.76173329,  41.89302675,
        41.87781186,  41.84301696,  41.91090083,  41.76208913,
        41.9082371 ,  41.79393591,  41.71184357,  41.81587521,
        41.91011672,  41.79070461,  41.92732184,  41.99596152,
        41.88993449,  41.7213798 ,  41.92527818,  41.83458618,
        41.81472107,  41.74089592,  41.88063228,  41.87851302,
        41.90528413,  41.94998639,  41.99458874,  41.7119596 ,
        41.82034323,  41.94333206,  41.77107306,  41.76991675,
        41.65324998,  41.78591319,  41.79204575,  41.72134702,
        41.94646154,  41.88165124,  41.73697442,  41.93382589,
        41.84114586,  41.7652989 ,  41.99370385,  41.8979804 ,
        41.77714211,  41.88945317,  41.91994998,  41.83638523,
        41.74271022,  41.91349864,  41.90465676,  41.9203601 ,
        41.81509317,  41.87891776,  41.86816541,  41.88

In [4]:
temp_df['Longitude'].unique()

array([-87.70681861, -87.60436317, -87.75837196, -87.74951598,
       -87.76175071, -87.6037989 , -87.62692325, -87.62074077,
       -87.66581404, -87.66387859, -87.55830998, -87.62675083,
       -87.65575801, -87.61722727, -87.68601875, -87.69663234,
       -87.67843742, -87.62568028, -87.64660793, -87.60183257,
       -87.67744465, -87.60614149, -87.66581042, -87.79752856,
       -87.63761923, -87.64978116, -87.65936796, -87.63228541,
       -87.7054583 , -87.64861788, -87.63593549, -87.76642478,
       -87.73261553, -87.65319658, -87.65752255, -87.61267363,
       -87.64175921, -87.70528607, -87.56827866, -87.66395498,
       -87.60482818, -87.69480165, -87.79713628, -87.65211853,
       -87.72072354, -87.62620049, -87.545828  , -87.78335189,
       -87.64148388, -87.58365451, -87.79418524, -87.63037668,
       -87.64714727, -87.62799483, -87.65164906, -87.66571041,
       -87.63408818, -87.77410994, -87.70763425, -87.68260517,
       -87.70425144, -87.72175831, -87.62743954, -87.62

In [5]:
not_empty_row = pd.notnull(temp_df['Latitude'])
not_empty_row

0       True
1       True
2       True
3       True
4       True
5       True
6       True
7       True
8       True
9       True
10      True
11      True
12      True
13      True
14      True
15      True
16      True
17      True
18      True
19      True
20      True
21      True
22      True
23      True
24      True
25      True
26      True
27      True
28      True
29      True
       ...  
169    False
170    False
171    False
172    False
173    False
174    False
175    False
176    False
177     True
178     True
179     True
180     True
181     True
182     True
183     True
184     True
185     True
186     True
187     True
188     True
189     True
190     True
191     True
192     True
193     True
194     True
195     True
196     True
197    False
198    False
Name: Latitude, dtype: bool

In [6]:
temp_df = temp_df[not_empty_row]
temp_df['Latitude'].unique()

array([ 41.86407316,  41.78292153,  41.89490828,  41.88568685,
        41.88629724,  41.74535402,  41.84402377,  41.81113396,
        41.99813061,  41.76809684,  41.76173329,  41.89302675,
        41.87781186,  41.84301696,  41.91090083,  41.76208913,
        41.9082371 ,  41.79393591,  41.71184357,  41.81587521,
        41.91011672,  41.79070461,  41.92732184,  41.99596152,
        41.88993449,  41.7213798 ,  41.92527818,  41.83458618,
        41.81472107,  41.74089592,  41.88063228,  41.87851302,
        41.90528413,  41.94998639,  41.99458874,  41.7119596 ,
        41.82034323,  41.94333206,  41.77107306,  41.76991675,
        41.65324998,  41.78591319,  41.79204575,  41.72134702,
        41.94646154,  41.88165124,  41.73697442,  41.93382589,
        41.84114586,  41.7652989 ,  41.99370385,  41.8979804 ,
        41.77714211,  41.88945317,  41.91994998,  41.83638523,
        41.74271022,  41.91349864,  41.90465676,  41.9203601 ,
        41.81509317,  41.87891776,  41.86816541,  41.88

In [7]:
# Cek for longitude
temp_df['Longitude'].unique()

array([-87.70681861, -87.60436317, -87.75837196, -87.74951598,
       -87.76175071, -87.6037989 , -87.62692325, -87.62074077,
       -87.66581404, -87.66387859, -87.55830998, -87.62675083,
       -87.65575801, -87.61722727, -87.68601875, -87.69663234,
       -87.67843742, -87.62568028, -87.64660793, -87.60183257,
       -87.67744465, -87.60614149, -87.66581042, -87.79752856,
       -87.63761923, -87.64978116, -87.65936796, -87.63228541,
       -87.7054583 , -87.64861788, -87.63593549, -87.76642478,
       -87.73261553, -87.65319658, -87.65752255, -87.61267363,
       -87.64175921, -87.70528607, -87.56827866, -87.66395498,
       -87.60482818, -87.69480165, -87.79713628, -87.65211853,
       -87.72072354, -87.62620049, -87.545828  , -87.78335189,
       -87.64148388, -87.58365451, -87.79418524, -87.63037668,
       -87.64714727, -87.62799483, -87.65164906, -87.66571041,
       -87.63408818, -87.77410994, -87.70763425, -87.68260517,
       -87.70425144, -87.72175831, -87.62743954, -87.62

In [8]:
unique_primary_type = temp_df['Primary Type'].unique()
unique_primary_type

array(['BATTERY', 'PUBLIC PEACE VIOLATION', 'THEFT', 'WEAPONS VIOLATION',
       'ROBBERY', 'MOTOR VEHICLE THEFT', 'ASSAULT', 'OTHER OFFENSE',
       'DECEPTIVE PRACTICE', 'CRIMINAL DAMAGE', 'CRIMINAL TRESPASS',
       'BURGLARY', 'STALKING', 'CRIM SEXUAL ASSAULT', 'NARCOTICS',
       'SEX OFFENSE', 'HOMICIDE'], dtype=object)

In [9]:
temp_df['Primary Type'].value_counts()

THEFT                     51
BATTERY                   25
DECEPTIVE PRACTICE        18
CRIMINAL DAMAGE           17
OTHER OFFENSE             11
ROBBERY                   10
ASSAULT                   10
MOTOR VEHICLE THEFT       10
BURGLARY                   5
WEAPONS VIOLATION          3
PUBLIC PEACE VIOLATION     3
NARCOTICS                  3
CRIMINAL TRESPASS          3
CRIM SEXUAL ASSAULT        2
HOMICIDE                   2
SEX OFFENSE                1
STALKING                   1
Name: Primary Type, dtype: int64

In [10]:
def normalization(x):
    mean = x.mean()
    std = x.std()
    temp = []
    for i in range(len(x)):
        val = x.iloc[i]
        temp.append((val-mean)/std)
    array = np.array(temp)
    return array

temp_df['Beat'] = normalization(temp_df['Beat'])
temp_df['District'] = normalization(temp_df['District'])
temp_df['Ward'] = normalization(temp_df['Ward'])
temp_df['Community Area'] = normalization(temp_df['Community Area'])
temp_df['Latitude'] = normalization(temp_df['Latitude'])
temp_df['Longitude'] = normalization(temp_df['Longitude'])

In [11]:
temp_df

Unnamed: 0        ID Case Number                Date                                Block  IUCR            Primary Type                              Description            Location Description Arrest Domestic      Beat  District      Ward  Community Area FBI Code  X Coordinate  Y Coordinate  Year       Updated On  Latitude  Longitude                       Location
0             3  10508693    HZ250496 2016-03-05 23:40:00                   013XX S SAWYER AVE   486                 BATTERY                  DOMESTIC BATTERY SIMPLE                       APARTMENT   True     True -0.228001 -0.225635  0.079274       -0.337226      08B     1154907.0     1893681.0  2016  5/10/2016 15:56  0.151780  -0.641015  (41.864073157, -87.706818608)
1            89  10508695    HZ250409 2016-03-05 21:40:00                   061XX S DREXEL AVE   486                 BATTERY                  DOMESTIC BATTERY SIMPLE                       RESIDENCE  False     True -1.202283 -1.188710 -0.192746        0.255198      08B     1183066.0     1864330.0  2016  5/10/2016 15:56 -0.777204   1.083238   (41.782921527, -87.60436317)
2           197  10508697    HZ250503 2016-03-05 23:31:00                  053XX W CHICAGO AVE   470  PUBLIC PEACE VIOLATION                         RECKLESS CONDUCT                          STREET  False    False  0.461829  0.462276  0.963340       -0.519510       24     1140789.0     1904819.0  2016  5/10/2016 15:56  0.504765  -1.508623  (41.894908283, -87.758371958)
3           673  10508698    HZ250424 2016-03-05 22:10:00                    049XX W FULTON ST   460                 BATTERY                                   SIMPLE                        SIDEWALK  False    False  0.472822  0.462276  0.351295       -0.519510      08B     1143223.0     1901475.0  2016  5/10/2016 15:56  0.399203  -1.359583  (41.885686845, -87.749515983)
4           911  10508699    HZ250455 2016-03-05 22:00:00                    003XX N LOTUS AVE   820                   THEFT                           $500 AND UNDER                       RESIDENCE  False     True  0.460455  0.462276  0.351295       -0.519510        6     1139890.0     1901675.0  2016  5/10/2016 15:56  0.406190  -1.565485  (41.886297242, -87.761750709)
5          1108  10508702    HZ250447 2016-03-05 22:35:00                 082XX S MARYLAND AVE  041A                 BATTERY                      AGGRAVATED: HANDGUN                          STREET  False    False -0.765299 -0.775963 -1.008806        0.346340      04B     1183336.0     1850642.0  2016  5/10/2016 15:56 -1.207259   1.092735  (41.745354023, -87.603798903)
6          1130  10508703    HZ250489 2016-03-05 22:30:00                     027XX S STATE ST   460                 BATTERY                                   SIMPLE  CHA HALLWAY/STAIRWELL/ELEVATOR  False    False -1.449632 -1.463874 -1.348831       -0.063799      08B     1176730.0     1886544.0  2016  5/10/2016 15:56 -0.077736   0.703568  (41.844023772, -87.626923253)
7          1801  10508704    HZ250514 2016-03-05 21:30:00                      002XX E 46TH ST   460                 BATTERY                                   SIMPLE         RESIDENCE PORCH/HALLWAY  False    False -1.336951 -1.326292 -1.348831        0.072914      08B     1178514.0     1874573.0  2016  5/10/2016 15:56 -0.454242   0.807615   (41.811133958, -87.62074077)
8          1868  10508709    HZ250523 2016-03-05 16:00:00                    014XX W DEVON AVE   460                 BATTERY                                   SIMPLE                        SIDEWALK  False    False  1.709569  1.700515  1.167355       -1.613215      08B     1165696.0     1942616.0  2016  5/10/2016 15:56  1.686404   0.049063   (41.99813061, -87.665814038)
9          1891  10508982    HZ250667 2016-03-05 22:30:00                  069XX S ASHLAND AVE   486                 BATTERY                  DOMESTIC BATTERY SIMPLE                          STREET  False     True -0.622386 -0.638381 -0.396761        1.394474      08B     1166876.0   

In [12]:
def getLevel(x, cls):
    cat = {}
    for i in range(len(x)):
        val = x.iloc[i]
        arrest = cls.iloc[i]
        if arrest:
            if val in cat:
                cat[val] -= 1
            else:
                cat[val] = 1
        else:
            if val in cat:
                cat[val] += 1
            else:
                cat[val] = 1
    level = 0
    final = {}
    len_of_cat = len(cat)
    for i in range(len_of_cat):
        minimum = min(cat, key=cat.get)
        final[minimum] = level
        cat.pop(minimum)
        level +=1
    return final

def getLevelDomestic(x, cls):
    cat = {}
    for i in range(len(x)):
        val = x.iloc[i]
        arrest = cls.iloc[i]
        if arrest:
            if val in cat:
                cat[val] += 1
            else:
                cat[val] = 1
        else:
            if val in cat:
                cat[val] -= 1
            else:
                cat[val] = 1
    level = 0
    final = {}
    len_of_cat = len(cat)
    for i in range(len_of_cat):
        minimum = min(cat, key=cat.get)
        final[minimum] = level
        cat.pop(minimum)
        level +=1
    return final

def normalizeCategorical(level, x):
    new = []
    for i in range(len(x)):
        val = x.iloc[i]
        new.append(level[val])
    return new
    
get_level_primetype = getLevel(temp_df['Primary Type'], temp_df['Arrest'])
get_level_locdesc = getLevel(temp_df['Location Description'], temp_df['Arrest'])
get_level_domestic = getLevelDomestic(temp_df['Domestic'], temp_df['Arrest'])

temp_df['Primary Type'] = normalizeCategorical(get_level_primetype, temp_df['Primary Type'])
temp_df['Location Description'] = normalizeCategorical(get_level_locdesc, temp_df['Location Description'])
temp_df['Domestic'] = normalizeCategorical(get_level_domestic, temp_df['Domestic'])

In [13]:
temp_df

Unnamed: 0        ID Case Number                Date                                Block  IUCR  Primary Type                              Description  Location Description Arrest  Domestic      Beat  District      Ward  Community Area FBI Code  X Coordinate  Y Coordinate  Year       Updated On  Latitude  Longitude                       Location
0             3  10508693    HZ250496 2016-03-05 23:40:00                   013XX S SAWYER AVE   486            15                  DOMESTIC BATTERY SIMPLE                    27   True         1 -0.228001 -0.225635  0.079274       -0.337226      08B     1154907.0     1893681.0  2016  5/10/2016 15:56  0.151780  -0.641015  (41.864073157, -87.706818608)
1            89  10508695    HZ250409 2016-03-05 21:40:00                   061XX S DREXEL AVE   486            15                  DOMESTIC BATTERY SIMPLE                    28  False         1 -1.202283 -1.188710 -0.192746        0.255198      08B     1183066.0     1864330.0  2016  5/10/2016 15:56 -0.777204   1.083238   (41.782921527, -87.60436317)
2           197  10508697    HZ250503 2016-03-05 23:31:00                  053XX W CHICAGO AVE   470             7                         RECKLESS CONDUCT                    29  False         0  0.461829  0.462276  0.963340       -0.519510       24     1140789.0     1904819.0  2016  5/10/2016 15:56  0.504765  -1.508623  (41.894908283, -87.758371958)
3           673  10508698    HZ250424 2016-03-05 22:10:00                    049XX W FULTON ST   460            15                                   SIMPLE                    25  False         0  0.472822  0.462276  0.351295       -0.519510      08B     1143223.0     1901475.0  2016  5/10/2016 15:56  0.399203  -1.359583  (41.885686845, -87.749515983)
4           911  10508699    HZ250455 2016-03-05 22:00:00                    003XX N LOTUS AVE   820            16                           $500 AND UNDER                    28  False         1  0.460455  0.462276  0.351295       -0.519510        6     1139890.0     1901675.0  2016  5/10/2016 15:56  0.406190  -1.565485  (41.886297242, -87.761750709)
5          1108  10508702    HZ250447 2016-03-05 22:35:00                 082XX S MARYLAND AVE  041A            15                      AGGRAVATED: HANDGUN                    29  False         0 -0.765299 -0.775963 -1.008806        0.346340      04B     1183336.0     1850642.0  2016  5/10/2016 15:56 -1.207259   1.092735  (41.745354023, -87.603798903)
6          1130  10508703    HZ250489 2016-03-05 22:30:00                     027XX S STATE ST   460            15                                   SIMPLE                     5  False         0 -1.449632 -1.463874 -1.348831       -0.063799      08B     1176730.0     1886544.0  2016  5/10/2016 15:56 -0.077736   0.703568  (41.844023772, -87.626923253)
7          1801  10508704    HZ250514 2016-03-05 21:30:00                      002XX E 46TH ST   460            15                                   SIMPLE                    20  False         0 -1.336951 -1.326292 -1.348831        0.072914      08B     1178514.0     1874573.0  2016  5/10/2016 15:56 -0.454242   0.807615   (41.811133958, -87.62074077)
8          1868  10508709    HZ250523 2016-03-05 16:00:00                    014XX W DEVON AVE   460            15                                   SIMPLE                    25  False         0  1.709569  1.700515  1.167355       -1.613215      08B     1165696.0     1942616.0  2016  5/10/2016 15:56  1.686404   0.049063   (41.99813061, -87.665814038)
9          1891  10508982    HZ250667 2016-03-05 22:30:00                  069XX S ASHLAND AVE   486            15                  DOMESTIC BATTERY SIMPLE                    29  False         1 -0.622386 -0.638381 -0.396761        1.394474      08B     1166876.0     1858796.0  2016  5/10/2016 15:56 -0.946910   0.081635  (41.768096835, -87.663878589)
10         1935  10508710    HZ250469 2016-03-05 21:44:00               074XX S SOUTH SHORE DR  143A             8        